tmp - trying without --build and without --gcp-project
Sourcing kube-util.sh
Detecting project
Project: gce-up-g1-3-clat-up-clu-n
Network Project: gce-up-g1-3-clat-up-clu-n
Zone: us-central1-b
Dumping logs from master locally to '/logs/artifacts/cluster-logs'
Trying to find master named 'kt2-d30067a4-5084-master'
Looking for address 'kt2-d30067a4-5084-master-ip'
ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
 - Required 'compute.addresses.get' permission for
   'projects/gce-up-g1-3-clat-up-clu-n/regions/us-central1/addresses/kt2-d30067a4-5084-master-ip'
Could not detect Kubernetes master node.  Make sure you've launched a
cluster with 'kube-up.sh'
Master not detected. Is the cluster up?
Dumping logs from nodes locally to '/logs/artifacts/cluster-logs'
Detecting nodes in the cluster
No nodes found!
ERROR: (gcloud.compute.instance-groups.managed.list) Some requests did
not succeed:
 - Required 'compute.instanceGroupManagers.list' permission for
   'projects/gce-up-g1-3-clat-up-clu-n'
ERROR: (gcloud.compute.instance-groups.managed.list) Some requests did
not succeed:
 - Required 'compute.instanceGroupManagers.list' permission for
   'projects/gce-up-g1-3-clat-up-clu-n'

Signed-off-by: Yoni Bettan <yonibettan@gmail.com>