tmp - adding assisted-installer gcp project
STATE:
Sourcing kube-util.sh
Detecting project
Project: assisted-installer
Network Project: assisted-installer
Zone: us-central1-b
Dumping logs from master locally to '/logs/artifacts/cluster-logs'
Trying to find master named 'kt2-d9f2b100-5076-master'
Looking for address 'kt2-d9f2b100-5076-master-ip'
ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
 - Required 'compute.addresses.get' permission for
   'projects/assisted-installer/regions/us-central1/addresses/kt2-d9f2b100-5076-master-ip'
Could not detect Kubernetes master node.  Make sure you've launched a
cluster with 'kube-up.sh'
Master not detected. Is the cluster up?

Signed-off-by: Yoni Bettan <yonibettan@gmail.com>