tmp - adding --build back
+++ [1020 13:06:20] Verifying Prerequisites....
Can't connect to 'docker' daemon.  please fix and retry.
Possible causes:
  - Docker Daemon not started
    - Linux: confirm via your init system
    - macOS w/ Docker for Mac: Check the menu bar and start the Docker
      application
  - DOCKER_HOST hasn't been set or is set incorrectly
    - Linux: domain socket is used, DOCKER_* should be unset. In Bash
      run `unset ${!DOCKER_*}`
    - macOS w/ Docker for Mac: domain socket is used, DOCKER_* should be
      unset. In Bash run `unset ${!DOCKER_*}`
  - Other things to check:
    - Linux: User isn't in 'docker' group.  Add and relogin.
      - Something like 'sudo usermod -a -G docker ${USER}'
      - RHEL7 bug and workaround:
        https://bugzilla.redhat.com/show_bug.cgi?id=1119282#c8
make: *** [Makefile:399: quick-release] Error 1
Error: exit status 2

Signed-off-by: Yoni Bettan <yonibettan@gmail.com>